### ISSUE TITLE
pug layouts and includes

### ISSUE THREAD

**Issue by alexwolfe** [cbkhalil/mspudding#7]
Assuming you've completed the other cleanup tasks. Lets move on to making some site wide layouts and includes using pug: 
1. Create a **layouts** folder in your development directory
2. Create a **includes** folder in your development directory 
3. Create a file called layout.pug in your **layouts** folder
4. Create the following files in your **includes** folder: 
   (navbar.pug, footer.pug, sidebar.pug)

I'll create another task for each one of these items.

**Comment by cbkhalil** [comment]
Working on turning these files into pug first (as I move css gradually into the giant stylesheet.css file). Minor progress being made!

**Comment by alexwolfe** [comment]
Great, please do one thing at a time so I can make more valuable comments. Please do not create pull requests that are outside the scope of this. For instance, I noticed that you didn't name the directories with these names and you also change the original side bar file that resides in production. Although I understand your reasoning for this, please refrain from doing so at this point since it will increase the time and slow down work. Those files will be deleted eventually anyway. 

I want you to create new files in the include and layouts directory even though they are not being used yet. Then we will integrate them and remove the other files in another pull request.
